name: "emsdk"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v14
      - uses: actions/checkout@v2

      - name: Build wasm file
        run: emcc -lembind -o pyra.js pyra.cpp -s ALLOW_MEMORY_GROWTH

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
